export type StatementType = 'income' | 'balance' | 'cashflow';

export type ConceptEntry = {
    label: string;
    statement: StatementType | StatementType[];
    negate?: boolean; // invert sign at extraction time (e.g. treasury stock, accumulated depreciation)
};

export const CONCEPT_MAP: Record<string, ConceptEntry> = {
    // ── Income Statement ──────────────────────────────────────────────────────
    'us-gaap:Revenues': { label: 'revenue', statement: 'income' },
    'us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax': { label: 'revenue', statement: 'income' },
    'us-gaap:RevenueFromContractWithCustomerIncludingAssessedTax': { label: 'revenue', statement: 'income' },
    'us-gaap:SalesRevenueNet': { label: 'revenue', statement: 'income' },
    'us-gaap:SalesRevenueGoodsNet': { label: 'product revenue', statement: 'income' },
    'us-gaap:SalesRevenueServicesNet': { label: 'service revenue', statement: 'income' },
    'us-gaap:CostOfRevenue': { label: 'cost of revenue', statement: 'income' },
    'us-gaap:CostOfGoodsAndServicesSold': { label: 'cost of revenue', statement: 'income' },
    'us-gaap:CostOfGoodsAndServiceExcludingDepreciationDepletionAndAmortization': { label: 'cost of revenue (excl. D&A)', statement: 'income' },
    'us-gaap:CostOfGoodsSold': { label: 'cost of goods sold', statement: 'income' },
    'us-gaap:CostOfServices': { label: 'cost of services', statement: 'income' },
    'us-gaap:GrossProfit': { label: 'gross profit', statement: 'income' },
    'us-gaap:ResearchAndDevelopmentExpense': { label: 'research and development', statement: 'income' },
    'us-gaap:ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost': { label: 'research and development', statement: 'income' },
    'us-gaap:SellingGeneralAndAdministrativeExpense': { label: 'selling, general and administrative', statement: 'income' },
    'us-gaap:SellingAndMarketingExpense': { label: 'sales and marketing', statement: 'income' },
    'us-gaap:GeneralAndAdministrativeExpense': { label: 'general and administrative', statement: 'income' },
    'us-gaap:OperatingExpenses': { label: 'total operating expenses', statement: 'income' },
    'us-gaap:CostsAndExpenses': { label: 'total costs and expenses', statement: 'income' },
    'us-gaap:DepreciationAndAmortization': { label: 'depreciation and amortization', statement: ['income', 'cashflow'] },
    'us-gaap:DepreciationDepletionAndAmortization': { label: 'depreciation, depletion and amortization', statement: ['income', 'cashflow'] },
    'us-gaap:AmortizationOfIntangibleAssets': { label: 'amortization of intangibles', statement: 'income' },
    'us-gaap:RestructuringCharges': { label: 'restructuring charges', statement: 'income' },
    'us-gaap:RestructuringAndRelatedCostIncurredCost': { label: 'restructuring charges', statement: 'income' },
    'us-gaap:ImpairmentOfLongLivedAssetsHeldForUse': { label: 'impairment charges', statement: 'income' },
    'us-gaap:GoodwillImpairmentLoss': { label: 'goodwill impairment', statement: 'income' },
    'us-gaap:OperatingIncomeLoss': { label: 'operating income', statement: 'income' },
    'us-gaap:NonoperatingIncomeExpense': { label: 'other income (expense)', statement: 'income' },
    'us-gaap:OtherNonoperatingIncomeExpense': { label: 'other non-operating income (expense)', statement: 'income' },
    'us-gaap:OtherOperatingIncomeExpenseNet': { label: 'other operating income (expense)', statement: 'income' },
    'us-gaap:InterestExpense': { label: 'interest expense', statement: 'income' },
    'us-gaap:InterestAndDebtExpense': { label: 'interest expense', statement: 'income' },
    'us-gaap:InterestExpenseDebt': { label: 'interest expense', statement: 'income' },
    'us-gaap:InterestIncome': { label: 'interest income', statement: 'income' },
    'us-gaap:InvestmentIncomeInterest': { label: 'interest income', statement: 'income' },
    'us-gaap:InterestIncomeExpenseNet': { label: 'interest income (expense), net', statement: 'income' },
    'us-gaap:InterestIncomeExpenseNonoperatingNet': { label: 'interest income (expense), net', statement: 'income' },
    'us-gaap:GainLossOnInvestments': { label: 'gain (loss) on investments', statement: 'income' },
    'us-gaap:GainLossOnSaleOfBusiness': { label: 'gain (loss) on sale of business', statement: 'income' },
    'us-gaap:GainLossOnDispositionOfAssets': { label: 'gain (loss) on asset disposals', statement: ['income', 'cashflow'] },
    'us-gaap:ImpairmentOfIntangibleAssetsExcludingGoodwill': { label: 'impairment of intangibles', statement: 'income' },
    'us-gaap:GainLossOnExtinguishmentOfDebt': { label: 'gain (loss) on extinguishment of debt', statement: 'income' },
    'us-gaap:ForeignCurrencyTransactionGainLossBeforeTax': { label: 'foreign currency gain (loss)', statement: 'income' },
    'us-gaap:LaborAndRelatedExpense': { label: 'labor and related expense', statement: 'income' },
    'us-gaap:OccupancyNet': { label: 'occupancy costs', statement: 'income' },
    'us-gaap:FoodAndBeverageCosts': { label: 'food and beverage costs', statement: 'income' },
    'us-gaap:FulfillmentExpense': { label: 'fulfillment', statement: 'income' },
    'us-gaap:TechnologyAndInfrastructure': { label: 'technology and infrastructure', statement: 'income' },
    'us-gaap:IncomeLossFromEquityMethodInvestments': { label: 'equity method investment income', statement: 'income' },
    'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest': { label: 'income before income taxes', statement: 'income' },
    'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments': { label: 'income before income taxes', statement: 'income' },
    'us-gaap:IncomeTaxExpenseBenefit': { label: 'income tax expense (benefit)', statement: 'income' },
    'us-gaap:IncomeLossFromContinuingOperations': { label: 'income from continuing operations', statement: 'income' },
    'us-gaap:ProfitLoss': { label: 'net income including noncontrolling interests', statement: 'income' },
    'us-gaap:NetIncomeLoss': { label: 'net income', statement: 'income' },
    'us-gaap:NetIncomeLossAttributableToNoncontrollingInterest': { label: 'net income attributable to noncontrolling interests', statement: 'income' },
    'us-gaap:NetIncomeLossAvailableToCommonStockholdersBasic': { label: 'net income attributable to common stockholders', statement: 'income' },
    'us-gaap:EarningsPerShareBasic': { label: 'earnings per share - basic', statement: 'income' },
    'us-gaap:EarningsPerShareDiluted': { label: 'earnings per share - diluted', statement: 'income' },
    // Share counts use U_shares unit (not USD) — unit filter is bypassed for concept-map entries
    'us-gaap:WeightedAverageNumberOfSharesOutstandingBasic': { label: 'weighted-average shares - basic', statement: 'income' },
    'us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding': { label: 'weighted-average shares - diluted', statement: 'income' },
    'us-gaap:WeightedAverageNumberOfSharesOutstandingDiluted': { label: 'weighted-average shares - diluted', statement: 'income' },
    'us-gaap:ComprehensiveIncomeNetOfTax': { label: 'comprehensive income', statement: 'income' },
    'us-gaap:OtherComprehensiveIncomeLossNetOfTax': { label: 'other comprehensive income (loss)', statement: 'income' },
    'us-gaap:ShareBasedCompensation': { label: 'stock-based compensation', statement: ['income', 'cashflow'] },

    // ── Balance Sheet ─────────────────────────────────────────────────────────
    'us-gaap:CashAndCashEquivalentsAtCarryingValue': { label: 'cash and cash equivalents', statement: 'balance' },
    'us-gaap:RestrictedCashAndCashEquivalentsCurrent': { label: 'restricted cash, current', statement: 'balance' },
    'us-gaap:RestrictedCashAndCashEquivalents': { label: 'restricted cash', statement: 'balance' },
    'us-gaap:RestrictedCash': { label: 'restricted cash', statement: 'balance' },
    'us-gaap:RestrictedCashCurrent': { label: 'restricted cash, current', statement: 'balance' },
    'us-gaap:CashCashEquivalentsAndShortTermInvestments': { label: 'cash, equivalents and short-term investments', statement: 'balance' },
    'us-gaap:ShortTermInvestments': { label: 'short-term investments', statement: 'balance' },
    'us-gaap:MarketableSecuritiesCurrent': { label: 'marketable securities, current', statement: 'balance' },
    'us-gaap:MarketableSecuritiesNoncurrent': { label: 'marketable securities, non-current', statement: 'balance' },
    'us-gaap:AvailableForSaleSecuritiesDebtSecuritiesCurrent': { label: 'available-for-sale securities, current', statement: 'balance' },
    'us-gaap:AccountsReceivableNetCurrent': { label: 'accounts receivable, net', statement: 'balance' },
    'us-gaap:ReceivablesNetCurrent': { label: 'receivables, net', statement: 'balance' },
    'us-gaap:ContractWithCustomerAssetNetCurrent': { label: 'contract assets, current', statement: 'balance' },
    'us-gaap:UnbilledReceivablesNotBillableAtBalanceSheetDate': { label: 'unbilled receivables', statement: 'balance' },
    'us-gaap:InventoryNet': { label: 'inventories', statement: 'balance' },
    'us-gaap:PrepaidExpenseAndOtherAssetsCurrent': { label: 'prepaid expenses and other current assets', statement: 'balance' },
    'us-gaap:OtherAssetsCurrent': { label: 'other current assets', statement: 'balance' },
    'us-gaap:AssetsCurrent': { label: 'total current assets', statement: 'balance' },
    'us-gaap:PropertyPlantAndEquipmentNet': { label: 'property, plant and equipment, net', statement: 'balance' },
    'us-gaap:PropertyPlantAndEquipmentGross': { label: 'property, plant and equipment, gross', statement: 'balance' },
    'us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment': { label: 'accumulated depreciation', statement: 'balance' },
    'us-gaap:Goodwill': { label: 'goodwill', statement: 'balance' },
    'us-gaap:IntangibleAssetsNetExcludingGoodwill': { label: 'intangible assets, net', statement: 'balance' },
    'us-gaap:FiniteLivedIntangibleAssetsNet': { label: 'intangible assets, net', statement: 'balance' },
    'us-gaap:OperatingLeaseRightOfUseAsset': { label: 'operating lease right-of-use assets', statement: 'balance' },
    'us-gaap:OtherAssetsNoncurrent': { label: 'other assets', statement: 'balance' },
    'us-gaap:DeferredIncomeTaxAssetsNet': { label: 'deferred tax assets', statement: 'balance' },
    'us-gaap:Assets': { label: 'total assets', statement: 'balance' },
    'us-gaap:AccountsPayableCurrent': { label: 'accounts payable', statement: 'balance' },
    'us-gaap:AccruedLiabilitiesCurrent': { label: 'accrued liabilities', statement: 'balance' },
    'us-gaap:EmployeeRelatedLiabilitiesCurrent': { label: 'accrued compensation', statement: 'balance' },
    'us-gaap:DeferredRevenueCurrent': { label: 'deferred revenue, current', statement: 'balance' },
    'us-gaap:ContractWithCustomerLiabilityCurrent': { label: 'deferred revenue, current', statement: 'balance' },
    'us-gaap:ShortTermBorrowings': { label: 'short-term borrowings', statement: 'balance' },
    'us-gaap:LongTermDebtCurrent': { label: 'current portion of long-term debt', statement: 'balance' },
    'us-gaap:LiabilitiesCurrent': { label: 'total current liabilities', statement: 'balance' },
    'us-gaap:LongTermDebtNoncurrent': { label: 'long-term debt', statement: 'balance' },
    'us-gaap:LongTermDebt': { label: 'long-term debt', statement: 'balance' },
    'us-gaap:LongTermDebtFairValue': { label: 'long-term debt', statement: 'balance' },
    'us-gaap:DebtLongtermAndShorttermCombinedAmount': { label: 'total debt', statement: 'balance' },
    'us-gaap:OperatingLeaseLiabilityNoncurrent': { label: 'operating lease liabilities, non-current', statement: 'balance' },
    'us-gaap:DeferredRevenueNoncurrent': { label: 'deferred revenue, non-current', statement: 'balance' },
    'us-gaap:ContractWithCustomerLiabilityNoncurrent': { label: 'deferred revenue, non-current', statement: 'balance' },
    'us-gaap:DeferredTaxLiabilitiesNoncurrent': { label: 'deferred tax liabilities', statement: 'balance' },
    'us-gaap:OtherLiabilitiesNoncurrent': { label: 'other liabilities', statement: 'balance' },
    'us-gaap:Liabilities': { label: 'total liabilities', statement: 'balance' },
    'us-gaap:CommonStockValue': { label: 'common stock', statement: 'balance' },
    'us-gaap:AdditionalPaidInCapital': { label: 'additional paid-in capital', statement: 'balance' },
    'us-gaap:RetainedEarningsAccumulatedDeficit': { label: 'retained earnings (accumulated deficit)', statement: 'balance' },
    'us-gaap:TreasuryStockValue': { label: 'treasury stock', statement: 'balance', negate: true },
    'us-gaap:TreasuryStockCommonValue': { label: 'treasury stock', statement: 'balance', negate: true },
    'us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax': { label: 'accumulated other comprehensive income (loss)', statement: 'balance' },
    'us-gaap:AccumulatedOtherComprehensiveIncomeLoss': { label: 'accumulated other comprehensive income (loss)', statement: 'balance' },
    'us-gaap:StockholdersEquity': { label: 'stockholders equity', statement: 'balance' },
    'us-gaap:MinorityInterest': { label: 'noncontrolling interests', statement: 'balance' },
    'us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest': { label: 'total equity', statement: 'balance' },
    'us-gaap:LiabilitiesAndStockholdersEquity': { label: 'total liabilities and equity', statement: 'balance' },

    // ── Balance Sheet — IFRS (ifrs-full namespace) ────────────────────────────
    'ifrs-full:CashAndCashEquivalents': { label: 'cash and cash equivalents', statement: 'balance' },
    'ifrs-full:FinancialAssetsAtFairValueThroughProfitOrLoss': { label: 'financial assets at fair value through profit or loss', statement: 'balance' },
    'ifrs-full:FinancialAssetsAtFairValueThroughOtherComprehensiveIncome': { label: 'financial assets at fair value through OCI', statement: 'balance' },
    'ifrs-full:FinancialAssetsAtAmortisedCost': { label: 'financial assets at amortised cost', statement: 'balance' },
    'ifrs-full:LoansAndAdvancesToCustomers': { label: 'loans and advances to customers', statement: 'balance' },
    'ifrs-full:LoansAndAdvancesToBanks': { label: 'loans and advances to banks', statement: 'balance' },
    'ifrs-full:OtherReceivables': { label: 'other receivables', statement: 'balance' },
    'ifrs-full:OtherAssets': { label: 'other assets', statement: 'balance' },
    'ifrs-full:DeferredTaxAssets': { label: 'deferred tax assets', statement: 'balance' },
    'ifrs-full:InvestmentsInAssociates': { label: 'investments in associates', statement: 'balance' },
    'ifrs-full:RightofuseAssets': { label: 'right-of-use assets', statement: 'balance' },
    'ifrs-full:PropertyPlantAndEquipment': { label: 'property, plant and equipment', statement: 'balance' },
    'ifrs-full:IntangibleAssetsOtherThanGoodwill': { label: 'intangible assets', statement: 'balance' },
    'ifrs-full:Goodwill': { label: 'goodwill', statement: 'balance' },
    'ifrs-full:Assets': { label: 'total assets', statement: 'balance' },
    'ifrs-full:DepositsFromCustomers': { label: 'deposits from customers', statement: 'balance' },
    'ifrs-full:DepositsFromBanks': { label: 'deposits from banks', statement: 'balance' },
    'ifrs-full:Borrowings': { label: 'borrowings', statement: 'balance' },
    'ifrs-full:ShorttermBorrowings': { label: 'short-term borrowings', statement: 'balance' },
    'ifrs-full:FinancialLiabilitiesAtFairValueThroughProfitOrLoss': { label: 'financial liabilities at fair value through profit or loss', statement: 'balance' },
    'ifrs-full:FinancialLiabilitiesAtAmortisedCost': { label: 'financial liabilities at amortised cost', statement: 'balance' },
    'ifrs-full:OtherLiabilities': { label: 'other liabilities', statement: 'balance' },
    'ifrs-full:OtherPayables': { label: 'other payables', statement: 'balance' },
    'ifrs-full:AccrualsAndDeferredIncomeIncludingContractLiabilities': { label: 'accruals and deferred income', statement: 'balance' },
    'ifrs-full:LegalProceedingsProvision': { label: 'provisions for legal proceedings', statement: 'balance' },
    'ifrs-full:Liabilities': { label: 'total liabilities', statement: 'balance' },
    'ifrs-full:IssuedCapital': { label: 'issued capital', statement: 'balance' },
    'ifrs-full:SharePremium': { label: 'share premium', statement: 'balance' },
    'ifrs-full:AccumulatedOtherComprehensiveIncome': { label: 'accumulated other comprehensive income (loss)', statement: 'balance' },
    'ifrs-full:EquityAttributableToOwnersOfParent': { label: 'equity attributable to owners of parent', statement: 'balance' },
    'ifrs-full:NoncontrollingInterests': { label: 'noncontrolling interests', statement: 'balance' },
    'ifrs-full:Equity': { label: 'total equity', statement: 'balance' },
    'ifrs-full:EquityAndLiabilities': { label: 'total equity and liabilities', statement: 'balance' },

    // ── Cash Flow ─────────────────────────────────────────────────────────────
    // Section totals — already signed in XBRL (positive = inflow, negative = outflow)
    'us-gaap:NetCashProvidedByUsedInOperatingActivities': { label: 'net cash from operating activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInOperatingActivitiesContinuingOperations': { label: 'net cash from operating activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInInvestingActivities': { label: 'net cash from investing activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInInvestingActivitiesContinuingOperations': { label: 'net cash from investing activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInFinancingActivities': { label: 'net cash from financing activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInFinancingActivitiesContinuingOperations': { label: 'net cash from financing activities', statement: 'cashflow' },
    'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect': { label: 'net change in cash', statement: 'cashflow' },
    'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseExcludingExchangeRateEffect': { label: 'net change in cash (excl. fx)', statement: 'cashflow' },
    'us-gaap:CashAndCashEquivalentsPeriodIncreaseDecrease': { label: 'net change in cash', statement: 'cashflow' },
    'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents': { label: 'cash end of period', statement: 'cashflow' },
    'us-gaap:EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents': { label: 'effect of exchange rate on cash', statement: 'cashflow' },

    // Operating — non-cash add-backs (already signed in XBRL)
    'us-gaap:DepreciationAmortizationAndAccretionNet': { label: 'depreciation, amortization and accretion', statement: 'cashflow' },
    'us-gaap:DeferredIncomeTaxExpenseBenefit': { label: 'deferred income taxes', statement: 'cashflow' },
    'us-gaap:ProvisionForLoanLeaseAndOtherLosses': { label: 'provision for credit losses', statement: 'cashflow' },
    'us-gaap:FinancingReceivableExcludingAccruedInterestCreditLossExpenseReversal': { label: 'credit loss expense', statement: 'cashflow' },
    'us-gaap:IncomeLossFromEquityMethodInvestmentsNetOfDividendsOrDistributions': { label: 'equity method investment income, net', statement: 'cashflow' },
    'us-gaap:GainLossOnDispositionOfAssets1': { label: 'gain (loss) on asset disposals', statement: 'cashflow' },
    'us-gaap:OtherNoncashIncomeExpense': { label: 'other non-cash items', statement: 'cashflow' },
    'us-gaap:InventoryWriteDown': { label: 'inventory write-down', statement: 'cashflow' },
    'us-gaap:AssetImpairmentCharges': { label: 'asset impairment charges', statement: 'cashflow' },
    'us-gaap:ProvisionForDoubtfulAccounts': { label: 'provision for credit losses', statement: 'cashflow' },
    'us-gaap:ProvisionForLoanAndLeaseLosses': { label: 'provision for credit losses', statement: 'cashflow' },
    'us-gaap:ProvisionForOtherCreditLosses': { label: 'provision for credit losses', statement: 'cashflow' },
    'us-gaap:AmortizationOfDebtDiscountPremium': { label: 'amortization of debt discount/premium', statement: 'cashflow' },
    'us-gaap:AmortizationOfFinancingCosts': { label: 'amortization of financing costs', statement: 'cashflow' },
    'us-gaap:AmortizationOfFinancingCostsAndDiscounts': { label: 'amortization of financing costs', statement: 'cashflow' },
    'us-gaap:ForeignCurrencyTransactionGainLossUnrealized': { label: 'unrealized foreign currency gain (loss)', statement: 'cashflow' },
    'us-gaap:EquitySecuritiesFvNiUnrealizedGainLoss': { label: 'unrealized gain (loss) on equity securities', statement: 'cashflow' },

    // Operating — working capital changes (already signed in XBRL)
    'us-gaap:IncreaseDecreaseInReceivables': { label: 'change in receivables', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccountsReceivable': { label: 'change in accounts receivable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInContractWithCustomerAsset': { label: 'change in contract assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInInventories': { label: 'change in inventories', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccountsPayable': { label: 'change in accounts payable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccountsPayableTrade': { label: 'change in accounts payable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccruedLiabilities': { label: 'change in accrued liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInEmployeeRelatedLiabilities': { label: 'change in accrued compensation', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccruedTaxesPayable': { label: 'change in accrued taxes', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInIncomeTaxesPayable': { label: 'change in income taxes payable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInIncomeTaxesReceivable': { label: 'change in income taxes receivable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInDeferredRevenue': { label: 'change in deferred revenue', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInContractWithCustomerLiability': { label: 'change in deferred revenue', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets': { label: 'change in prepaid and other assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherOperatingAssets': { label: 'change in other operating assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherOperatingLiabilities': { label: 'change in other operating liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherCurrentAssets': { label: 'change in other current assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherCurrentLiabilities': { label: 'change in other current liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherNoncurrentAssets': { label: 'change in other non-current assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherNoncurrentLiabilities': { label: 'change in other non-current liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOperatingLeaseLiability': { label: 'change in operating lease liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOperatingCapital': { label: 'change in operating capital', statement: 'cashflow' },
    'us-gaap:OtherOperatingActivitiesCashFlowStatement': { label: 'other operating activities', statement: 'cashflow' },

    // Pension — outflow, negate
    'us-gaap:PensionContributions': { label: 'pension contributions', statement: 'cashflow', negate: true },

    // Investing — outflows (Payments*), negate; inflows (Proceeds*), keep as-is
    'us-gaap:PaymentsToAcquirePropertyPlantAndEquipment': { label: 'capital expenditures', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsToAcquireBusinessesNetOfCashAcquired': { label: 'acquisitions, net of cash', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsToAcquireIntangibleAssets': { label: 'purchases of intangible assets', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsToAcquireInvestments': { label: 'purchases of investments', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsToAcquireAvailableForSaleSecurities': { label: 'purchases of investments', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsToAcquireAvailableForSaleSecuritiesDebt': { label: 'purchases of investments', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsForProceedsFromOtherInvestingActivities': { label: 'other investing activities', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleOfPropertyPlantAndEquipment': { label: 'proceeds from asset sales', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleOfProductiveAssets': { label: 'proceeds from asset sales', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleMaturityAndCollectionsOfInvestments': { label: 'proceeds from investments', statement: 'cashflow' },
    'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities': { label: 'maturities of investments', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleOfAvailableForSaleSecurities': { label: 'proceeds from sales of investments', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleOfAvailableForSaleSecuritiesDebt': { label: 'proceeds from sales of AFS securities', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleAndMaturityOfAvailableForSaleSecurities': { label: 'proceeds from investments', statement: 'cashflow' },
    'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfHeldToMaturitySecurities': { label: 'maturities of HTM securities', statement: 'cashflow' },
    'us-gaap:PaymentsToAcquireHeldToMaturitySecurities': { label: 'purchases of HTM securities', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsForOriginationAndPurchasesOfLoansHeldForSale': { label: 'originations of loans held for sale', statement: 'cashflow', negate: true },
    'us-gaap:ProceedsFromSaleOfFinanceReceivables': { label: 'proceeds from loan sales', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInDeposits': { label: 'change in deposits', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInFederalFundsPurchasedAndSecuritiesSoldUnderAgreementsToRepurchaseNet': { label: 'change in repos and fed funds purchased', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInFinancialInstrumentsUsedInOperatingActivities': { label: 'change in trading assets and liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInTradingLiabilities': { label: 'change in trading liabilities', statement: 'cashflow' },
    'us-gaap:ProceedsFromPaymentsForFederalFundsSoldAndSecuritiesPurchasedUnderAgreementsToResellNet': { label: 'net change in fed funds sold and reverse repos', statement: 'cashflow' },

    // Financing — outflows (Payments*, Repayments*), negate; inflows (Proceeds*), keep as-is
    'us-gaap:PaymentsForRepurchaseOfCommonStock': { label: 'repurchase of common stock', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsOfDividends': { label: 'dividends paid', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsOfDividendsCommonStock': { label: 'dividends paid - common', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsOfDividendsPreferredStockAndPreferenceStock': { label: 'dividends paid - preferred', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsOfDividendsMinorityInterest': { label: 'dividends to noncontrolling interests', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsToMinorityShareholders': { label: 'payments to noncontrolling interests', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsOfDebtIssuanceCosts': { label: 'debt issuance costs paid', statement: 'cashflow', negate: true },
    'us-gaap:RepaymentsOfLongTermDebt': { label: 'repayments of long-term debt', statement: 'cashflow', negate: true },
    'us-gaap:RepaymentsOfLinesOfCredit': { label: 'repayments of revolving credit', statement: 'cashflow', negate: true },
    'us-gaap:RepaymentsOfShortTermDebt': { label: 'repayments of short-term debt', statement: 'cashflow', negate: true },
    'us-gaap:FinanceLeasePrincipalPayments': { label: 'finance lease principal payments', statement: 'cashflow', negate: true },
    'us-gaap:PaymentsRelatedToTaxWithholdingForShareBasedCompensation': { label: 'tax withholding on stock awards', statement: 'cashflow', negate: true },
    'us-gaap:ProceedsFromStockOptionsExercised': { label: 'proceeds from stock option exercises', statement: 'cashflow' },
    'us-gaap:ProceedsFromIssuanceOfLongTermDebt': { label: 'proceeds from long-term debt', statement: 'cashflow' },
    'us-gaap:ProceedsFromLinesOfCredit': { label: 'proceeds from revolving credit', statement: 'cashflow' },
    'us-gaap:ProceedsFromShortTermDebt': { label: 'proceeds from short-term debt', statement: 'cashflow' },
    'us-gaap:ProceedsFromShortTermDebtMaturingInMoreThanThreeMonths': { label: 'proceeds from short-term debt', statement: 'cashflow' },
    'us-gaap:RepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths': { label: 'repayments of short-term debt', statement: 'cashflow', negate: true },
    'us-gaap:ProceedsFromRepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess': { label: 'net short-term debt (≤3 months)', statement: 'cashflow' },
    'us-gaap:ProceedsFromRepaymentsOfCommercialPaper': { label: 'net commercial paper', statement: 'cashflow' },
    'us-gaap:ProceedsFromMinorityShareholders': { label: 'proceeds from noncontrolling interests', statement: 'cashflow' },
    'us-gaap:ProceedsFromIssuanceOfCommonStock': { label: 'proceeds from issuance of common stock', statement: 'cashflow' },
    'us-gaap:ProceedsFromPaymentsForOtherFinancingActivities': { label: 'other financing activities', statement: 'cashflow' },
    'us-gaap:ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': { label: 'proceeds from long-term debt', statement: 'cashflow' },
    'us-gaap:RepaymentsOfLongTermDebtAndCapitalSecurities': { label: 'repayments of long-term debt', statement: 'cashflow', negate: true },
};

// ── Sector-specific concept groups ────────────────────────────────────────────
// ALL sectors are always merged into the effective concept map at parse time.
// Companies only report concepts relevant to their own industry, so cross-sector
// concepts never appear in unrelated filings — no CIK-to-sector mapping needed.
// Only include concepts NOT already in the global CONCEPT_MAP above.

export const SECTOR_CONCEPTS: Record<string, Record<string, ConceptEntry>> = {
    energy: {
        'us-gaap:CrudeOilAndProductPurchases': { label: 'crude oil and product purchases', statement: 'income' },
        'us-gaap:ProductionAndManufacturingExpense': { label: 'production and manufacturing', statement: 'income' },
        'us-gaap:ExplorationExpense': { label: 'exploration expense', statement: 'income' },
        'us-gaap:OilAndGasProductionExpense': { label: 'oil and gas production expense', statement: 'income' },
        'us-gaap:TaxesExcludingIncomeAndExciseTaxes': { label: 'taxes other than income taxes', statement: 'income' },
        'us-gaap:ResultsOfOperationsProductionOrLiftingCosts': { label: 'lifting costs', statement: 'income' },
    },
    restaurant: {
        'us-gaap:FoodAndBeverageRevenue': { label: 'food and beverage revenue', statement: 'income' },
        'us-gaap:PreOpeningCosts': { label: 'pre-opening costs', statement: 'income' },
    },
    ecommerce: {
        'us-gaap:MarketingExpense': { label: 'marketing', statement: 'income' },
    },
    logistics: {
        'us-gaap:FuelCosts': { label: 'fuel', statement: 'income' },
        'us-gaap:PurchasedTransportation': { label: 'purchased transportation', statement: 'income' },
    },
    semiconductor: {
        'us-gaap:ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost': { label: 'research and development', statement: 'income' },
        'us-gaap:CostOfGoodsSold': { label: 'cost of revenue', statement: 'income' },
    },
    financial: {
        // Revenue — net interest income + non-interest income is the top line for banks
        'us-gaap:RevenuesNetOfInterestExpense': { label: 'net revenue', statement: 'income' },
        'us-gaap:NoninterestIncome': { label: 'non-interest income', statement: 'income' },
        'us-gaap:NoninterestIncomeOther': { label: 'other non-interest income', statement: 'income' },
        // Interest income / expense detail
        'us-gaap:InterestIncomeOperating': { label: 'interest income', statement: 'income' },
        'us-gaap:InterestAndFeeIncomeLoansAndLeases': { label: 'interest and fee income - loans', statement: 'income' },
        'us-gaap:InterestIncomeDepositsWithFinancialInstitutions': { label: 'interest income - deposits', statement: 'income' },
        'us-gaap:InterestIncomeSecuritiesTaxable': { label: 'interest income - taxable securities', statement: 'income' },
        'us-gaap:InterestIncomeSecuritiesTaxExempt': { label: 'interest income - tax-exempt securities', statement: 'income' },
        'us-gaap:InterestIncomeFederalFundsSoldAndSecuritiesPurchasedUnderAgreementsToResell': { label: 'interest income - fed funds sold and reverse repos', statement: 'income' },
        'us-gaap:InterestExpenseDeposits': { label: 'interest expense - deposits', statement: 'income', negate: true },
        'us-gaap:InterestExpenseLongTermDebt': { label: 'interest expense - long-term debt', statement: 'income', negate: true },
        'us-gaap:InterestExpenseFederalFundsPurchasedAndSecuritiesSoldUnderAgreementsToRepurchase': { label: 'interest expense - repos and fed funds', statement: 'income', negate: true },
        'us-gaap:InterestExpenseShortTermBorrowings': { label: 'interest expense - short-term borrowings', statement: 'income', negate: true },
        'us-gaap:InterestIncomeExpenseAfterProvisionForLoanLoss': { label: 'net interest income after provision', statement: 'income' },
        // Credit losses
        'us-gaap:ProvisionForLoanLeaseAndOtherLosses': { label: 'provision for credit losses', statement: 'income' },
        // Capital markets / fee income
        'us-gaap:TradingGainsLosses': { label: 'trading gains/losses', statement: 'income' },
        'us-gaap:PrincipalTransactionsRevenue': { label: 'principal transactions', statement: 'income' },
        'us-gaap:InvestmentBankingRevenue': { label: 'investment banking revenue', statement: 'income' },
        'us-gaap:BrokerageCommissionsRevenue': { label: 'brokerage commissions', statement: 'income' },
        'us-gaap:UnderwritingIncomeLoss': { label: 'underwriting income/loss', statement: 'income' },
        // Non-interest expense detail
        'us-gaap:NoninterestExpense': { label: 'total non-interest expense', statement: 'income' },
        'us-gaap:OtherNoninterestExpense': { label: 'other non-interest expense', statement: 'income' },
        'us-gaap:CommunicationsAndInformationTechnology': { label: 'technology and communications', statement: 'income' },
        'us-gaap:ProfessionalAndContractServicesExpense': { label: 'professional services', statement: 'income' },
        'us-gaap:MarketingAndAdvertisingExpense': { label: 'marketing and advertising', statement: 'income' },
    },
};

