export type StatementType = 'income' | 'balance' | 'cashflow';

export type ConceptEntry = {
    label: string;
    statement: StatementType | StatementType[];
};

export const CONCEPT_MAP: Record<string, ConceptEntry> = {
    // ── Income Statement ──────────────────────────────────────────────────────
    'us-gaap:Revenues': { label: 'revenue', statement: 'income' },
    'us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax': { label: 'revenue', statement: 'income' },
    'us-gaap:RevenueFromContractWithCustomerIncludingAssessedTax': { label: 'revenue', statement: 'income' },
    'us-gaap:SalesRevenueNet': { label: 'revenue', statement: 'income' },
    'us-gaap:SalesRevenueGoodsNet': { label: 'product revenue', statement: 'income' },
    'us-gaap:SalesRevenueServicesNet': { label: 'service revenue', statement: 'income' },
    'us-gaap:CostOfRevenue': { label: 'cost of revenue', statement: 'income' },
    'us-gaap:CostOfGoodsAndServicesSold': { label: 'cost of revenue', statement: 'income' },
    'us-gaap:CostOfGoodsAndServiceExcludingDepreciationDepletionAndAmortization': { label: 'cost of revenue (excl. D&A)', statement: 'income' },
    'us-gaap:CostOfGoodsSold': { label: 'cost of goods sold', statement: 'income' },
    'us-gaap:CostOfServices': { label: 'cost of services', statement: 'income' },
    'us-gaap:GrossProfit': { label: 'gross profit', statement: 'income' },
    'us-gaap:ResearchAndDevelopmentExpense': { label: 'research and development', statement: 'income' },
    'us-gaap:ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost': { label: 'research and development', statement: 'income' },
    'us-gaap:SellingGeneralAndAdministrativeExpense': { label: 'selling, general and administrative', statement: 'income' },
    'us-gaap:SellingAndMarketingExpense': { label: 'sales and marketing', statement: 'income' },
    'us-gaap:GeneralAndAdministrativeExpense': { label: 'general and administrative', statement: 'income' },
    'us-gaap:OperatingExpenses': { label: 'total operating expenses', statement: 'income' },
    'us-gaap:CostsAndExpenses': { label: 'total costs and expenses', statement: 'income' },
    'us-gaap:DepreciationAndAmortization': { label: 'depreciation and amortization', statement: ['income', 'cashflow'] },
    'us-gaap:DepreciationDepletionAndAmortization': { label: 'depreciation, depletion and amortization', statement: ['income', 'cashflow'] },
    'us-gaap:AmortizationOfIntangibleAssets': { label: 'amortization of intangibles', statement: 'income' },
    'us-gaap:RestructuringCharges': { label: 'restructuring charges', statement: 'income' },
    'us-gaap:RestructuringAndRelatedCostIncurredCost': { label: 'restructuring charges', statement: 'income' },
    'us-gaap:ImpairmentOfLongLivedAssetsHeldForUse': { label: 'impairment charges', statement: 'income' },
    'us-gaap:GoodwillImpairmentLoss': { label: 'goodwill impairment', statement: 'income' },
    'us-gaap:OperatingIncomeLoss': { label: 'operating income', statement: 'income' },
    'us-gaap:NonoperatingIncomeExpense': { label: 'other income (expense)', statement: 'income' },
    'us-gaap:OtherNonoperatingIncomeExpense': { label: 'other non-operating income (expense)', statement: 'income' },
    'us-gaap:OtherOperatingIncomeExpenseNet': { label: 'other operating income (expense)', statement: 'income' },
    'us-gaap:InterestExpense': { label: 'interest expense', statement: 'income' },
    'us-gaap:InterestAndDebtExpense': { label: 'interest expense', statement: 'income' },
    'us-gaap:InterestIncome': { label: 'interest income', statement: 'income' },
    'us-gaap:InterestIncomeExpenseNet': { label: 'interest income (expense), net', statement: 'income' },
    'us-gaap:InterestIncomeExpenseNonoperatingNet': { label: 'interest income (expense), net', statement: 'income' },
    'us-gaap:IncomeLossFromEquityMethodInvestments': { label: 'equity method investment income', statement: 'income' },
    'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest': { label: 'income before income taxes', statement: 'income' },
    'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments': { label: 'income before income taxes', statement: 'income' },
    'us-gaap:IncomeTaxExpenseBenefit': { label: 'income tax expense (benefit)', statement: 'income' },
    'us-gaap:IncomeLossFromContinuingOperations': { label: 'income from continuing operations', statement: 'income' },
    'us-gaap:ProfitLoss': { label: 'net income including noncontrolling interests', statement: 'income' },
    'us-gaap:NetIncomeLoss': { label: 'net income', statement: 'income' },
    'us-gaap:NetIncomeLossAttributableToNoncontrollingInterest': { label: 'net income attributable to noncontrolling interests', statement: 'income' },
    'us-gaap:NetIncomeLossAvailableToCommonStockholdersBasic': { label: 'net income attributable to common stockholders', statement: 'income' },
    'us-gaap:EarningsPerShareBasic': { label: 'earnings per share - basic', statement: 'income' },
    'us-gaap:EarningsPerShareDiluted': { label: 'earnings per share - diluted', statement: 'income' },
    'us-gaap:WeightedAverageNumberOfSharesOutstandingBasic': { label: 'weighted-average shares - basic', statement: 'income' },
    'us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding': { label: 'weighted-average shares - diluted', statement: 'income' },
    'us-gaap:ComprehensiveIncomeNetOfTax': { label: 'comprehensive income', statement: 'income' },
    'us-gaap:OtherComprehensiveIncomeLossNetOfTax': { label: 'other comprehensive income (loss)', statement: 'income' },
    'us-gaap:ShareBasedCompensation': { label: 'stock-based compensation', statement: ['income', 'cashflow'] },

    // ── Balance Sheet ─────────────────────────────────────────────────────────
    'us-gaap:CashAndCashEquivalentsAtCarryingValue': { label: 'cash and cash equivalents', statement: 'balance' },
    'us-gaap:CashCashEquivalentsAndShortTermInvestments': { label: 'cash, equivalents and short-term investments', statement: 'balance' },
    'us-gaap:ShortTermInvestments': { label: 'short-term investments', statement: 'balance' },
    'us-gaap:MarketableSecuritiesCurrent': { label: 'marketable securities, current', statement: 'balance' },
    'us-gaap:MarketableSecuritiesNoncurrent': { label: 'marketable securities, non-current', statement: 'balance' },
    'us-gaap:AvailableForSaleSecuritiesDebtSecuritiesCurrent': { label: 'available-for-sale securities, current', statement: 'balance' },
    'us-gaap:AccountsReceivableNetCurrent': { label: 'accounts receivable, net', statement: 'balance' },
    'us-gaap:ReceivablesNetCurrent': { label: 'receivables, net', statement: 'balance' },
    'us-gaap:InventoryNet': { label: 'inventories', statement: 'balance' },
    'us-gaap:PrepaidExpenseAndOtherAssetsCurrent': { label: 'prepaid expenses and other current assets', statement: 'balance' },
    'us-gaap:OtherAssetsCurrent': { label: 'other current assets', statement: 'balance' },
    'us-gaap:AssetsCurrent': { label: 'total current assets', statement: 'balance' },
    'us-gaap:PropertyPlantAndEquipmentNet': { label: 'property, plant and equipment, net', statement: 'balance' },
    'us-gaap:PropertyPlantAndEquipmentGross': { label: 'property, plant and equipment, gross', statement: 'balance' },
    'us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment': { label: 'accumulated depreciation', statement: 'balance' },
    'us-gaap:Goodwill': { label: 'goodwill', statement: 'balance' },
    'us-gaap:IntangibleAssetsNetExcludingGoodwill': { label: 'intangible assets, net', statement: 'balance' },
    'us-gaap:FiniteLivedIntangibleAssetsNet': { label: 'intangible assets, net', statement: 'balance' },
    'us-gaap:OperatingLeaseRightOfUseAsset': { label: 'operating lease right-of-use assets', statement: 'balance' },
    'us-gaap:OtherAssetsNoncurrent': { label: 'other assets', statement: 'balance' },
    'us-gaap:DeferredIncomeTaxAssetsNet': { label: 'deferred tax assets', statement: 'balance' },
    'us-gaap:Assets': { label: 'total assets', statement: 'balance' },
    'us-gaap:AccountsPayableCurrent': { label: 'accounts payable', statement: 'balance' },
    'us-gaap:AccruedLiabilitiesCurrent': { label: 'accrued liabilities', statement: 'balance' },
    'us-gaap:EmployeeRelatedLiabilitiesCurrent': { label: 'accrued compensation', statement: 'balance' },
    'us-gaap:DeferredRevenueCurrent': { label: 'deferred revenue, current', statement: 'balance' },
    'us-gaap:ContractWithCustomerLiabilityCurrent': { label: 'deferred revenue, current', statement: 'balance' },
    'us-gaap:ShortTermBorrowings': { label: 'short-term borrowings', statement: 'balance' },
    'us-gaap:LongTermDebtCurrent': { label: 'current portion of long-term debt', statement: 'balance' },
    'us-gaap:LiabilitiesCurrent': { label: 'total current liabilities', statement: 'balance' },
    'us-gaap:LongTermDebtNoncurrent': { label: 'long-term debt', statement: 'balance' },
    'us-gaap:LongTermDebt': { label: 'long-term debt', statement: 'balance' },
    'us-gaap:DebtLongtermAndShorttermCombinedAmount': { label: 'total debt', statement: 'balance' },
    'us-gaap:OperatingLeaseLiabilityNoncurrent': { label: 'operating lease liabilities, non-current', statement: 'balance' },
    'us-gaap:DeferredRevenueNoncurrent': { label: 'deferred revenue, non-current', statement: 'balance' },
    'us-gaap:ContractWithCustomerLiabilityNoncurrent': { label: 'deferred revenue, non-current', statement: 'balance' },
    'us-gaap:DeferredTaxLiabilitiesNoncurrent': { label: 'deferred tax liabilities', statement: 'balance' },
    'us-gaap:OtherLiabilitiesNoncurrent': { label: 'other liabilities', statement: 'balance' },
    'us-gaap:Liabilities': { label: 'total liabilities', statement: 'balance' },
    'us-gaap:CommonStockValue': { label: 'common stock', statement: 'balance' },
    'us-gaap:AdditionalPaidInCapital': { label: 'additional paid-in capital', statement: 'balance' },
    'us-gaap:RetainedEarningsAccumulatedDeficit': { label: 'retained earnings (accumulated deficit)', statement: 'balance' },
    'us-gaap:TreasuryStockValue': { label: 'treasury stock', statement: 'balance' },
    'us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax': { label: 'accumulated other comprehensive income (loss)', statement: 'balance' },
    'us-gaap:StockholdersEquity': { label: 'stockholders equity', statement: 'balance' },
    'us-gaap:MinorityInterest': { label: 'noncontrolling interests', statement: 'balance' },
    'us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest': { label: 'total equity', statement: 'balance' },
    'us-gaap:LiabilitiesAndStockholdersEquity': { label: 'total liabilities and equity', statement: 'balance' },

    // ── Cash Flow ─────────────────────────────────────────────────────────────
    'us-gaap:NetCashProvidedByUsedInOperatingActivities': { label: 'net cash from operating activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInInvestingActivities': { label: 'net cash from investing activities', statement: 'cashflow' },
    'us-gaap:NetCashProvidedByUsedInFinancingActivities': { label: 'net cash from financing activities', statement: 'cashflow' },
    'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect': { label: 'net change in cash', statement: 'cashflow' },
    'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseExcludingExchangeRateEffect': { label: 'net change in cash (excl. fx)', statement: 'cashflow' },
    'us-gaap:CashAndCashEquivalentsPeriodIncreaseDecrease': { label: 'net change in cash', statement: 'cashflow' },
    'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents': { label: 'cash end of period', statement: 'cashflow' },
    'us-gaap:EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents': { label: 'effect of exchange rate on cash', statement: 'cashflow' },
    'us-gaap:DeferredIncomeTaxExpenseBenefit': { label: 'deferred income taxes', statement: 'cashflow' },
    'us-gaap:IncomeLossFromEquityMethodInvestmentsNetOfDividendsOrDistributions': { label: 'equity method investment income, net', statement: 'cashflow' },
    'us-gaap:GainLossOnDispositionOfAssets': { label: 'gain (loss) on asset disposals', statement: 'cashflow' },
    'us-gaap:GainLossOnDispositionOfAssets1': { label: 'gain (loss) on asset disposals', statement: 'cashflow' },
    'us-gaap:OtherNoncashIncomeExpense': { label: 'other non-cash items', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInReceivables': { label: 'change in receivables', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccountsReceivable': { label: 'change in accounts receivable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInInventories': { label: 'change in inventories', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccountsPayable': { label: 'change in accounts payable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccountsPayableTrade': { label: 'change in accounts payable', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccruedLiabilities': { label: 'change in accrued liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInAccruedTaxesPayable': { label: 'change in accrued taxes', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInDeferredRevenue': { label: 'change in deferred revenue', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInContractWithCustomerLiability': { label: 'change in deferred revenue', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets': { label: 'change in prepaid and other assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherNoncurrentAssets': { label: 'change in other non-current assets', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOtherNoncurrentLiabilities': { label: 'change in other non-current liabilities', statement: 'cashflow' },
    'us-gaap:IncreaseDecreaseInOperatingCapital': { label: 'change in operating capital', statement: 'cashflow' },
    'us-gaap:PensionContributions': { label: 'pension contributions', statement: 'cashflow' },
    'us-gaap:OtherOperatingActivitiesCashFlowStatement': { label: 'other operating activities', statement: 'cashflow' },
    'us-gaap:PaymentsToAcquirePropertyPlantAndEquipment': { label: 'capital expenditures', statement: 'cashflow' },
    'us-gaap:PaymentsToAcquireBusinessesNetOfCashAcquired': { label: 'acquisitions, net of cash', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleOfPropertyPlantAndEquipment': { label: 'proceeds from asset sales', statement: 'cashflow' },
    'us-gaap:PaymentsToAcquireInvestments': { label: 'purchases of investments', statement: 'cashflow' },
    'us-gaap:ProceedsFromSaleMaturityAndCollectionsOfInvestments': { label: 'proceeds from investments', statement: 'cashflow' },
    'us-gaap:PaymentsForProceedsFromOtherInvestingActivities': { label: 'other investing activities', statement: 'cashflow' },
    'us-gaap:PaymentsForRepurchaseOfCommonStock': { label: 'repurchase of common stock', statement: 'cashflow' },
    'us-gaap:ProceedsFromStockOptionsExercised': { label: 'proceeds from stock option exercises', statement: 'cashflow' },
    'us-gaap:PaymentsOfDividends': { label: 'dividends paid', statement: 'cashflow' },
    'us-gaap:PaymentsOfDividendsCommonStock': { label: 'dividends paid - common', statement: 'cashflow' },
    'us-gaap:PaymentsOfDividendsPreferredStockAndPreferenceStock': { label: 'dividends paid - preferred', statement: 'cashflow' },
    'us-gaap:PaymentsOfDividendsMinorityInterest': { label: 'dividends to noncontrolling interests', statement: 'cashflow' },
    'us-gaap:ProceedsFromMinorityShareholders': { label: 'proceeds from noncontrolling interests', statement: 'cashflow' },
    'us-gaap:ProceedsFromPaymentsForOtherFinancingActivities': { label: 'other financing activities', statement: 'cashflow' },
    'us-gaap:ProceedsFromIssuanceOfLongTermDebt': { label: 'proceeds from long-term debt', statement: 'cashflow' },
    'us-gaap:RepaymentsOfLongTermDebt': { label: 'repayments of long-term debt', statement: 'cashflow' },
    'us-gaap:ProceedsFromLinesOfCredit': { label: 'proceeds from revolving credit', statement: 'cashflow' },
    'us-gaap:RepaymentsOfLinesOfCredit': { label: 'repayments of revolving credit', statement: 'cashflow' },
    'us-gaap:ProceedsFromShortTermDebt': { label: 'proceeds from short-term debt', statement: 'cashflow' },
    'us-gaap:RepaymentsOfShortTermDebt': { label: 'repayments of short-term debt', statement: 'cashflow' },
    'us-gaap:PaymentsRelatedToTaxWithholdingForShareBasedCompensation': { label: 'tax withholding on stock awards', statement: 'cashflow' },
};
